/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.style.book.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.function.UnsafeFunction;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.change.tracking.CTService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.service.persistence.change.tracking.CTPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.style.book.model.StyleBookToken;
import com.liferay.style.book.service.StyleBookTokenLocalService;
import com.liferay.style.book.service.persistence.StyleBookTokenPersistence;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the style book token local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.style.book.service.impl.StyleBookTokenLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.style.book.service.impl.StyleBookTokenLocalServiceImpl
 * @generated
 */
public abstract class StyleBookTokenLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, StyleBookTokenLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>StyleBookTokenLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.style.book.service.StyleBookTokenLocalServiceUtil</code>.
	 */

	/**
	 * Adds the style book token to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect StyleBookTokenLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param styleBookToken the style book token
	 * @return the style book token that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public StyleBookToken addStyleBookToken(StyleBookToken styleBookToken) {
		styleBookToken.setNew(true);

		return styleBookTokenPersistence.update(styleBookToken);
	}

	/**
	 * Creates a new style book token with the primary key. Does not add the style book token to the database.
	 *
	 * @param styleBookTokenId the primary key for the new style book token
	 * @return the new style book token
	 */
	@Override
	@Transactional(enabled = false)
	public StyleBookToken createStyleBookToken(long styleBookTokenId) {
		return styleBookTokenPersistence.create(styleBookTokenId);
	}

	/**
	 * Deletes the style book token with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect StyleBookTokenLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param styleBookTokenId the primary key of the style book token
	 * @return the style book token that was removed
	 * @throws PortalException if a style book token with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public StyleBookToken deleteStyleBookToken(long styleBookTokenId)
		throws PortalException {

		return styleBookTokenPersistence.remove(styleBookTokenId);
	}

	/**
	 * Deletes the style book token from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect StyleBookTokenLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param styleBookToken the style book token
	 * @return the style book token that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public StyleBookToken deleteStyleBookToken(StyleBookToken styleBookToken) {
		return styleBookTokenPersistence.remove(styleBookToken);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return styleBookTokenPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			StyleBookToken.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return styleBookTokenPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.style.book.model.impl.StyleBookTokenModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return styleBookTokenPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.style.book.model.impl.StyleBookTokenModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return styleBookTokenPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return styleBookTokenPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return styleBookTokenPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public StyleBookToken fetchStyleBookToken(long styleBookTokenId) {
		return styleBookTokenPersistence.fetchByPrimaryKey(styleBookTokenId);
	}

	/**
	 * Returns the style book token matching the UUID and group.
	 *
	 * @param uuid the style book token's UUID
	 * @param groupId the primary key of the group
	 * @return the matching style book token, or <code>null</code> if a matching style book token could not be found
	 */
	@Override
	public StyleBookToken fetchStyleBookTokenByUuidAndGroupId(
		String uuid, long groupId) {

		return styleBookTokenPersistence.fetchByUUID_G(uuid, groupId);
	}

	@Override
	public StyleBookToken fetchStyleBookTokenByExternalReferenceCode(
		String externalReferenceCode, long groupId) {

		return styleBookTokenPersistence.fetchByERC_G(
			externalReferenceCode, groupId);
	}

	@Override
	public StyleBookToken getStyleBookTokenByExternalReferenceCode(
			String externalReferenceCode, long groupId)
		throws PortalException {

		return styleBookTokenPersistence.findByERC_G(
			externalReferenceCode, groupId);
	}

	/**
	 * Returns the style book token with the primary key.
	 *
	 * @param styleBookTokenId the primary key of the style book token
	 * @return the style book token
	 * @throws PortalException if a style book token with the primary key could not be found
	 */
	@Override
	public StyleBookToken getStyleBookToken(long styleBookTokenId)
		throws PortalException {

		return styleBookTokenPersistence.findByPrimaryKey(styleBookTokenId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(styleBookTokenLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(StyleBookToken.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("styleBookTokenId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			styleBookTokenLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(StyleBookToken.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"styleBookTokenId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(styleBookTokenLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(StyleBookToken.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("styleBookTokenId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<StyleBookToken>() {

				@Override
				public void performAction(StyleBookToken styleBookToken)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, styleBookToken);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(StyleBookToken.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return styleBookTokenPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement StyleBookTokenLocalServiceImpl#deleteStyleBookToken(StyleBookToken) to avoid orphaned data");
		}

		return styleBookTokenLocalService.deleteStyleBookToken(
			(StyleBookToken)persistedModel);
	}

	@Override
	public BasePersistence<StyleBookToken> getBasePersistence() {
		return styleBookTokenPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return styleBookTokenPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the style book tokens matching the UUID and company.
	 *
	 * @param uuid the UUID of the style book tokens
	 * @param companyId the primary key of the company
	 * @return the matching style book tokens, or an empty list if no matches were found
	 */
	@Override
	public List<StyleBookToken> getStyleBookTokensByUuidAndCompanyId(
		String uuid, long companyId) {

		return styleBookTokenPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of style book tokens matching the UUID and company.
	 *
	 * @param uuid the UUID of the style book tokens
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of style book tokens
	 * @param end the upper bound of the range of style book tokens (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching style book tokens, or an empty list if no matches were found
	 */
	@Override
	public List<StyleBookToken> getStyleBookTokensByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<StyleBookToken> orderByComparator) {

		return styleBookTokenPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the style book token matching the UUID and group.
	 *
	 * @param uuid the style book token's UUID
	 * @param groupId the primary key of the group
	 * @return the matching style book token
	 * @throws PortalException if a matching style book token could not be found
	 */
	@Override
	public StyleBookToken getStyleBookTokenByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return styleBookTokenPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the style book tokens.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.style.book.model.impl.StyleBookTokenModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of style book tokens
	 * @param end the upper bound of the range of style book tokens (not inclusive)
	 * @return the range of style book tokens
	 */
	@Override
	public List<StyleBookToken> getStyleBookTokens(int start, int end) {
		return styleBookTokenPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of style book tokens.
	 *
	 * @return the number of style book tokens
	 */
	@Override
	public int getStyleBookTokensCount() {
		return styleBookTokenPersistence.countAll();
	}

	/**
	 * Updates the style book token in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect StyleBookTokenLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param styleBookToken the style book token
	 * @return the style book token that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public StyleBookToken updateStyleBookToken(StyleBookToken styleBookToken) {
		return styleBookTokenPersistence.update(styleBookToken);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			StyleBookTokenLocalService.class, IdentifiableOSGiService.class,
			CTService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		styleBookTokenLocalService = (StyleBookTokenLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return StyleBookTokenLocalService.class.getName();
	}

	@Override
	public CTPersistence<StyleBookToken> getCTPersistence() {
		return styleBookTokenPersistence;
	}

	@Override
	public Class<StyleBookToken> getModelClass() {
		return StyleBookToken.class;
	}

	@Override
	public <R, E extends Throwable> R updateWithUnsafeFunction(
			UnsafeFunction<CTPersistence<StyleBookToken>, R, E>
				updateUnsafeFunction)
		throws E {

		return updateUnsafeFunction.apply(styleBookTokenPersistence);
	}

	protected String getModelClassName() {
		return StyleBookToken.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = styleBookTokenPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected StyleBookTokenLocalService styleBookTokenLocalService;

	@Reference
	protected StyleBookTokenPersistence styleBookTokenPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		StyleBookTokenLocalServiceBaseImpl.class);

}
// LIFERAY-SERVICE-BUILDER-HASH:-1976465163