create table StyleBookEntry (
	mvccVersion LONG default 0 not null,
	ctCollectionId LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	externalReferenceCode VARCHAR(75) null,
	headId LONG,
	head BOOLEAN,
	styleBookEntryId LONG not null,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	defaultStyleBookEntry BOOLEAN,
	frontendTokensValues TEXT null,
	name VARCHAR(75) null,
	previewFileEntryId LONG,
	styleBookEntryKey VARCHAR(75) null,
	themeId VARCHAR(255) null,
	primary key (styleBookEntryId, ctCollectionId)
);

create table StyleBookEntryVersion (
	mvccVersion LONG default 0 not null,
	ctCollectionId LONG default 0 not null,
	styleBookEntryVersionId LONG not null,
	version INTEGER,
	uuid_ VARCHAR(75) null,
	externalReferenceCode VARCHAR(75) null,
	styleBookEntryId LONG,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	defaultStyleBookEntry BOOLEAN,
	frontendTokensValues TEXT null,
	name VARCHAR(75) null,
	previewFileEntryId LONG,
	styleBookEntryKey VARCHAR(75) null,
	themeId VARCHAR(255) null,
	primary key (styleBookEntryVersionId, ctCollectionId)
);

create table StyleBookToken (
	mvccVersion LONG default 0 not null,
	ctCollectionId LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	externalReferenceCode VARCHAR(75) null,
	styleBookTokenId LONG not null,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	styleBookTokenSetId LONG,
	description STRING null,
	name VARCHAR(75) null,
	tokenKey VARCHAR(75) null,
	type_ VARCHAR(75) null,
	value VARCHAR(75) null,
	primary key (styleBookTokenId, ctCollectionId)
);

create table StyleBookTokenSet (
	mvccVersion LONG default 0 not null,
	ctCollectionId LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	externalReferenceCode VARCHAR(75) null,
	styleBookTokenSetId LONG not null,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	styleBookEntryId LONG,
	description STRING null,
	frontendTokenCategoryName VARCHAR(75) null,
	name VARCHAR(75) null,
	themeId VARCHAR(75) null,
	primary key (styleBookTokenSetId, ctCollectionId)
);