/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.style.book.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ExternalReferenceCodeModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.change.tracking.CTModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the StyleBookToken service. Represents a row in the &quot;StyleBookToken&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.style.book.model.impl.StyleBookTokenModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.style.book.model.impl.StyleBookTokenImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StyleBookToken
 * @generated
 */
@ProviderType
public interface StyleBookTokenModel
	extends BaseModel<StyleBookToken>, CTModel<StyleBookToken>,
			ExternalReferenceCodeModel, GroupedModel, MVCCModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a style book token model instance should use the {@link StyleBookToken} interface instead.
	 */

	/**
	 * Returns the primary key of this style book token.
	 *
	 * @return the primary key of this style book token
	 */
	@Override
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this style book token.
	 *
	 * @param primaryKey the primary key of this style book token
	 */
	@Override
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this style book token.
	 *
	 * @return the mvcc version of this style book token
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this style book token.
	 *
	 * @param mvccVersion the mvcc version of this style book token
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the ct collection ID of this style book token.
	 *
	 * @return the ct collection ID of this style book token
	 */
	@Override
	public long getCtCollectionId();

	/**
	 * Sets the ct collection ID of this style book token.
	 *
	 * @param ctCollectionId the ct collection ID of this style book token
	 */
	@Override
	public void setCtCollectionId(long ctCollectionId);

	/**
	 * Returns the uuid of this style book token.
	 *
	 * @return the uuid of this style book token
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this style book token.
	 *
	 * @param uuid the uuid of this style book token
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the external reference code of this style book token.
	 *
	 * @return the external reference code of this style book token
	 */
	@AutoEscape
	@Override
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this style book token.
	 *
	 * @param externalReferenceCode the external reference code of this style book token
	 */
	@Override
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the style book token ID of this style book token.
	 *
	 * @return the style book token ID of this style book token
	 */
	public long getStyleBookTokenId();

	/**
	 * Sets the style book token ID of this style book token.
	 *
	 * @param styleBookTokenId the style book token ID of this style book token
	 */
	public void setStyleBookTokenId(long styleBookTokenId);

	/**
	 * Returns the group ID of this style book token.
	 *
	 * @return the group ID of this style book token
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this style book token.
	 *
	 * @param groupId the group ID of this style book token
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this style book token.
	 *
	 * @return the company ID of this style book token
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this style book token.
	 *
	 * @param companyId the company ID of this style book token
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this style book token.
	 *
	 * @return the user ID of this style book token
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this style book token.
	 *
	 * @param userId the user ID of this style book token
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this style book token.
	 *
	 * @return the user uuid of this style book token
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this style book token.
	 *
	 * @param userUuid the user uuid of this style book token
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this style book token.
	 *
	 * @return the user name of this style book token
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this style book token.
	 *
	 * @param userName the user name of this style book token
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this style book token.
	 *
	 * @return the create date of this style book token
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this style book token.
	 *
	 * @param createDate the create date of this style book token
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this style book token.
	 *
	 * @return the modified date of this style book token
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this style book token.
	 *
	 * @param modifiedDate the modified date of this style book token
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the style book token set ID of this style book token.
	 *
	 * @return the style book token set ID of this style book token
	 */
	public long getStyleBookTokenSetId();

	/**
	 * Sets the style book token set ID of this style book token.
	 *
	 * @param styleBookTokenSetId the style book token set ID of this style book token
	 */
	public void setStyleBookTokenSetId(long styleBookTokenSetId);

	/**
	 * Returns the description of this style book token.
	 *
	 * @return the description of this style book token
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this style book token.
	 *
	 * @param description the description of this style book token
	 */
	public void setDescription(String description);

	/**
	 * Returns the name of this style book token.
	 *
	 * @return the name of this style book token
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this style book token.
	 *
	 * @param name the name of this style book token
	 */
	public void setName(String name);

	/**
	 * Returns the token key of this style book token.
	 *
	 * @return the token key of this style book token
	 */
	@AutoEscape
	public String getTokenKey();

	/**
	 * Sets the token key of this style book token.
	 *
	 * @param tokenKey the token key of this style book token
	 */
	public void setTokenKey(String tokenKey);

	/**
	 * Returns the type of this style book token.
	 *
	 * @return the type of this style book token
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this style book token.
	 *
	 * @param type the type of this style book token
	 */
	public void setType(String type);

	/**
	 * Returns the value of this style book token.
	 *
	 * @return the value of this style book token
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this style book token.
	 *
	 * @param value the value of this style book token
	 */
	public void setValue(String value);

	@Override
	public StyleBookToken cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:1499466832