/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.style.book.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.style.book.model.StyleBookToken;
import com.liferay.style.book.model.StyleBookTokenModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the StyleBookToken service. Represents a row in the &quot;StyleBookToken&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>StyleBookTokenModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StyleBookTokenImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StyleBookTokenImpl
 * @generated
 */
@JSON(strict = true)
public class StyleBookTokenModelImpl
	extends BaseModelImpl<StyleBookToken> implements StyleBookTokenModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a style book token model instance should use the <code>StyleBookToken</code> interface instead.
	 */
	public static final String TABLE_NAME = "StyleBookToken";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ctCollectionId", Types.BIGINT},
		{"uuid_", Types.VARCHAR}, {"externalReferenceCode", Types.VARCHAR},
		{"styleBookTokenId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"styleBookTokenSetId", Types.BIGINT}, {"description", Types.VARCHAR},
		{"name", Types.VARCHAR}, {"tokenKey", Types.VARCHAR},
		{"type_", Types.VARCHAR}, {"value", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("styleBookTokenId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("styleBookTokenSetId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("tokenKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("value", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table StyleBookToken (mvccVersion LONG default 0 not null,ctCollectionId LONG default 0 not null,uuid_ VARCHAR(75) null,externalReferenceCode VARCHAR(75) null,styleBookTokenId LONG not null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,styleBookTokenSetId LONG,description STRING null,name VARCHAR(75) null,tokenKey VARCHAR(75) null,type_ VARCHAR(75) null,value VARCHAR(75) null,primary key (styleBookTokenId, ctCollectionId))";

	public static final String TABLE_SQL_DROP = "drop table StyleBookToken";

	public static final String ENTITY_ALIAS = "styleBookToken";

	public static final String ORDER_BY_JPQL =
		" ORDER BY styleBookToken.name ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY StyleBookToken.name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXTERNALREFERENCECODE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STYLEBOOKTOKENSETID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TOKENKEY_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public StyleBookTokenModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _styleBookTokenId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setStyleBookTokenId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _styleBookTokenId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return StyleBookToken.class;
	}

	@Override
	public String getModelClassName() {
		return StyleBookToken.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<StyleBookToken, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<StyleBookToken, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<StyleBookToken, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((StyleBookToken)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<StyleBookToken, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<StyleBookToken, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(StyleBookToken)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<StyleBookToken, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<StyleBookToken, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<StyleBookToken, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<StyleBookToken, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<StyleBookToken, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", StyleBookToken::getMvccVersion);
			attributeGetterFunctions.put(
				"ctCollectionId", StyleBookToken::getCtCollectionId);
			attributeGetterFunctions.put("uuid", StyleBookToken::getUuid);
			attributeGetterFunctions.put(
				"externalReferenceCode",
				StyleBookToken::getExternalReferenceCode);
			attributeGetterFunctions.put(
				"styleBookTokenId", StyleBookToken::getStyleBookTokenId);
			attributeGetterFunctions.put("groupId", StyleBookToken::getGroupId);
			attributeGetterFunctions.put(
				"companyId", StyleBookToken::getCompanyId);
			attributeGetterFunctions.put("userId", StyleBookToken::getUserId);
			attributeGetterFunctions.put(
				"userName", StyleBookToken::getUserName);
			attributeGetterFunctions.put(
				"createDate", StyleBookToken::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", StyleBookToken::getModifiedDate);
			attributeGetterFunctions.put(
				"styleBookTokenSetId", StyleBookToken::getStyleBookTokenSetId);
			attributeGetterFunctions.put(
				"description", StyleBookToken::getDescription);
			attributeGetterFunctions.put("name", StyleBookToken::getName);
			attributeGetterFunctions.put(
				"tokenKey", StyleBookToken::getTokenKey);
			attributeGetterFunctions.put("type", StyleBookToken::getType);
			attributeGetterFunctions.put("value", StyleBookToken::getValue);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<StyleBookToken, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<StyleBookToken, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<StyleBookToken, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<StyleBookToken, Long>)
					StyleBookToken::setMvccVersion);
			attributeSetterBiConsumers.put(
				"ctCollectionId",
				(BiConsumer<StyleBookToken, Long>)
					StyleBookToken::setCtCollectionId);
			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<StyleBookToken, String>)StyleBookToken::setUuid);
			attributeSetterBiConsumers.put(
				"externalReferenceCode",
				(BiConsumer<StyleBookToken, String>)
					StyleBookToken::setExternalReferenceCode);
			attributeSetterBiConsumers.put(
				"styleBookTokenId",
				(BiConsumer<StyleBookToken, Long>)
					StyleBookToken::setStyleBookTokenId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<StyleBookToken, Long>)StyleBookToken::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<StyleBookToken, Long>)StyleBookToken::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<StyleBookToken, Long>)StyleBookToken::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<StyleBookToken, String>)
					StyleBookToken::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<StyleBookToken, Date>)
					StyleBookToken::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<StyleBookToken, Date>)
					StyleBookToken::setModifiedDate);
			attributeSetterBiConsumers.put(
				"styleBookTokenSetId",
				(BiConsumer<StyleBookToken, Long>)
					StyleBookToken::setStyleBookTokenSetId);
			attributeSetterBiConsumers.put(
				"description",
				(BiConsumer<StyleBookToken, String>)
					StyleBookToken::setDescription);
			attributeSetterBiConsumers.put(
				"name",
				(BiConsumer<StyleBookToken, String>)StyleBookToken::setName);
			attributeSetterBiConsumers.put(
				"tokenKey",
				(BiConsumer<StyleBookToken, String>)
					StyleBookToken::setTokenKey);
			attributeSetterBiConsumers.put(
				"type",
				(BiConsumer<StyleBookToken, String>)StyleBookToken::setType);
			attributeSetterBiConsumers.put(
				"value",
				(BiConsumer<StyleBookToken, String>)StyleBookToken::setValue);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ctCollectionId = ctCollectionId;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public String getExternalReferenceCode() {
		if (_externalReferenceCode == null) {
			return "";
		}
		else {
			return _externalReferenceCode;
		}
	}

	@Override
	public void setExternalReferenceCode(String externalReferenceCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalReferenceCode = externalReferenceCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalExternalReferenceCode() {
		return getColumnOriginalValue("externalReferenceCode");
	}

	@JSON
	@Override
	public long getStyleBookTokenId() {
		return _styleBookTokenId;
	}

	@Override
	public void setStyleBookTokenId(long styleBookTokenId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_styleBookTokenId = styleBookTokenId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getStyleBookTokenSetId() {
		return _styleBookTokenSetId;
	}

	@Override
	public void setStyleBookTokenSetId(long styleBookTokenSetId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_styleBookTokenSetId = styleBookTokenSetId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalStyleBookTokenSetId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("styleBookTokenSetId"));
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public String getTokenKey() {
		if (_tokenKey == null) {
			return "";
		}
		else {
			return _tokenKey;
		}
	}

	@Override
	public void setTokenKey(String tokenKey) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tokenKey = tokenKey;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalTokenKey() {
		return getColumnOriginalValue("tokenKey");
	}

	@JSON
	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	@JSON
	@Override
	public String getValue() {
		if (_value == null) {
			return "";
		}
		else {
			return _value;
		}
	}

	@Override
	public void setValue(String value) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_value = value;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(StyleBookToken.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), StyleBookToken.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public StyleBookToken toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, StyleBookToken>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		StyleBookTokenImpl styleBookTokenImpl = new StyleBookTokenImpl();

		styleBookTokenImpl.setMvccVersion(getMvccVersion());
		styleBookTokenImpl.setCtCollectionId(getCtCollectionId());
		styleBookTokenImpl.setUuid(getUuid());
		styleBookTokenImpl.setExternalReferenceCode(getExternalReferenceCode());
		styleBookTokenImpl.setStyleBookTokenId(getStyleBookTokenId());
		styleBookTokenImpl.setGroupId(getGroupId());
		styleBookTokenImpl.setCompanyId(getCompanyId());
		styleBookTokenImpl.setUserId(getUserId());
		styleBookTokenImpl.setUserName(getUserName());
		styleBookTokenImpl.setCreateDate(getCreateDate());
		styleBookTokenImpl.setModifiedDate(getModifiedDate());
		styleBookTokenImpl.setStyleBookTokenSetId(getStyleBookTokenSetId());
		styleBookTokenImpl.setDescription(getDescription());
		styleBookTokenImpl.setName(getName());
		styleBookTokenImpl.setTokenKey(getTokenKey());
		styleBookTokenImpl.setType(getType());
		styleBookTokenImpl.setValue(getValue());

		styleBookTokenImpl.resetOriginalValues();

		return styleBookTokenImpl;
	}

	@Override
	public StyleBookToken cloneWithOriginalValues() {
		StyleBookTokenImpl styleBookTokenImpl = new StyleBookTokenImpl();

		styleBookTokenImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		styleBookTokenImpl.setCtCollectionId(
			this.<Long>getColumnOriginalValue("ctCollectionId"));
		styleBookTokenImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		styleBookTokenImpl.setExternalReferenceCode(
			this.<String>getColumnOriginalValue("externalReferenceCode"));
		styleBookTokenImpl.setStyleBookTokenId(
			this.<Long>getColumnOriginalValue("styleBookTokenId"));
		styleBookTokenImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		styleBookTokenImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		styleBookTokenImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		styleBookTokenImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		styleBookTokenImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		styleBookTokenImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		styleBookTokenImpl.setStyleBookTokenSetId(
			this.<Long>getColumnOriginalValue("styleBookTokenSetId"));
		styleBookTokenImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		styleBookTokenImpl.setName(this.<String>getColumnOriginalValue("name"));
		styleBookTokenImpl.setTokenKey(
			this.<String>getColumnOriginalValue("tokenKey"));
		styleBookTokenImpl.setType(
			this.<String>getColumnOriginalValue("type_"));
		styleBookTokenImpl.setValue(
			this.<String>getColumnOriginalValue("value"));

		return styleBookTokenImpl;
	}

	@Override
	public int compareTo(StyleBookToken styleBookToken) {
		int value = 0;

		value = getName().compareTo(styleBookToken.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof StyleBookToken)) {
			return false;
		}

		StyleBookToken styleBookToken = (StyleBookToken)object;

		long primaryKey = styleBookToken.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<StyleBookToken> toCacheModel() {
		StyleBookTokenCacheModel styleBookTokenCacheModel =
			new StyleBookTokenCacheModel();

		styleBookTokenCacheModel.mvccVersion = getMvccVersion();

		styleBookTokenCacheModel.ctCollectionId = getCtCollectionId();

		styleBookTokenCacheModel.uuid = getUuid();

		String uuid = styleBookTokenCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			styleBookTokenCacheModel.uuid = null;
		}

		styleBookTokenCacheModel.externalReferenceCode =
			getExternalReferenceCode();

		String externalReferenceCode =
			styleBookTokenCacheModel.externalReferenceCode;

		if ((externalReferenceCode != null) &&
			(externalReferenceCode.length() == 0)) {

			styleBookTokenCacheModel.externalReferenceCode = null;
		}

		styleBookTokenCacheModel.styleBookTokenId = getStyleBookTokenId();

		styleBookTokenCacheModel.groupId = getGroupId();

		styleBookTokenCacheModel.companyId = getCompanyId();

		styleBookTokenCacheModel.userId = getUserId();

		styleBookTokenCacheModel.userName = getUserName();

		String userName = styleBookTokenCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			styleBookTokenCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			styleBookTokenCacheModel.createDate = createDate.getTime();
		}
		else {
			styleBookTokenCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			styleBookTokenCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			styleBookTokenCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		styleBookTokenCacheModel.styleBookTokenSetId = getStyleBookTokenSetId();

		styleBookTokenCacheModel.description = getDescription();

		String description = styleBookTokenCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			styleBookTokenCacheModel.description = null;
		}

		styleBookTokenCacheModel.name = getName();

		String name = styleBookTokenCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			styleBookTokenCacheModel.name = null;
		}

		styleBookTokenCacheModel.tokenKey = getTokenKey();

		String tokenKey = styleBookTokenCacheModel.tokenKey;

		if ((tokenKey != null) && (tokenKey.length() == 0)) {
			styleBookTokenCacheModel.tokenKey = null;
		}

		styleBookTokenCacheModel.type = getType();

		String type = styleBookTokenCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			styleBookTokenCacheModel.type = null;
		}

		styleBookTokenCacheModel.value = getValue();

		String value = styleBookTokenCacheModel.value;

		if ((value != null) && (value.length() == 0)) {
			styleBookTokenCacheModel.value = null;
		}

		return styleBookTokenCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<StyleBookToken, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<StyleBookToken, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<StyleBookToken, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((StyleBookToken)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, StyleBookToken>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					StyleBookToken.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _ctCollectionId;
	private String _uuid;
	private String _externalReferenceCode;
	private long _styleBookTokenId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _styleBookTokenSetId;
	private String _description;
	private String _name;
	private String _tokenKey;
	private String _type;
	private String _value;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<StyleBookToken, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((StyleBookToken)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("ctCollectionId", _ctCollectionId);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"externalReferenceCode", _externalReferenceCode);
		_columnOriginalValues.put("styleBookTokenId", _styleBookTokenId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("styleBookTokenSetId", _styleBookTokenSetId);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("tokenKey", _tokenKey);
		_columnOriginalValues.put("type_", _type);
		_columnOriginalValues.put("value", _value);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("type_", "type");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("ctCollectionId", 2L);

		columnBitmasks.put("uuid_", 4L);

		columnBitmasks.put("externalReferenceCode", 8L);

		columnBitmasks.put("styleBookTokenId", 16L);

		columnBitmasks.put("groupId", 32L);

		columnBitmasks.put("companyId", 64L);

		columnBitmasks.put("userId", 128L);

		columnBitmasks.put("userName", 256L);

		columnBitmasks.put("createDate", 512L);

		columnBitmasks.put("modifiedDate", 1024L);

		columnBitmasks.put("styleBookTokenSetId", 2048L);

		columnBitmasks.put("description", 4096L);

		columnBitmasks.put("name", 8192L);

		columnBitmasks.put("tokenKey", 16384L);

		columnBitmasks.put("type_", 32768L);

		columnBitmasks.put("value", 65536L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private StyleBookToken _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-2114213240